// Usage: npm run verify:env
// Writes .env.verify: TEST-ONLY settings for `npm run verify:start`. It points at the local
// throwaway database and uses a made-up admin password, so verification never touches
// real data or real secrets. The file is git-ignored (.env*).
import { randomBytes } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { hashPassword } from '@/lib/admin/password';

export const VERIFY_PASSWORD = 'verify-password-123';

async function main() {
  const databaseUrl = execFileSync('scripts/db.sh', ['url', 'test'], { encoding: 'utf8' }).trim();
  const lines = [
    '# TEST-ONLY values for local verification. Generated by `npm run verify:env`.',
    `DATABASE_URL=${databaseUrl}`,
    `ADMIN_PASSWORD_HASH=${await hashPassword(VERIFY_PASSWORD)}`,
    `SESSION_SECRET=${randomBytes(32).toString('hex')}`,
    'OPENAI_API_KEY=verify-placeholder',
    'STRIPE_SECRET_KEY=verify-placeholder',
    // Only for the real-upload check (`npm run verify:upload`): development Blob stores, never production ones.
    ...(process.env.VERIFY_BLOB_PUBLIC_TOKEN && process.env.VERIFY_BLOB_PRIVATE_TOKEN
      ? [`BLOB_PUBLIC_TOKEN=${process.env.VERIFY_BLOB_PUBLIC_TOKEN}`, `BLOB_PRIVATE_TOKEN=${process.env.VERIFY_BLOB_PRIVATE_TOKEN}`]
      : []),
    '',
  ];
  writeFileSync('.env.verify', lines.join('\n'));
  console.log(`wrote .env.verify (admin password for verification: ${VERIFY_PASSWORD})`);
}

main().catch((error) => {
  console.error(`FAIL: ${error instanceof Error ? error.message : String(error)}`);
  process.exit(1);
});
